services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: QRCode
      POSTGRES_PASSWORD: QRCode
      POSTGRES_DB: QRCode
    restart: always
    networks:
      - lesson
networks:
  lesson: